[target.'cfg(target_os = "none")']
runner = "cargo-image"

[build]
target = "x86_64-titanium.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]